version: "3.8"

services:
  # api container
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
    environment:
      - DB_HOST=postgres
      - DB_PASSWORD=123456
    # чтобы не передеплоить каждый раз контейнер, если были изменения в коде
    volumes:
      - ./src:/src
      - ./tests:/tests
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # db container
  postgres:
    build:
      context: docker
      dockerfile: Dockerfile-db
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB_NAME=dev_test
      - POSTGRES_SCHEMA_NAME=public
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
