version: "3.8"

services:
  # db container
  postgres:
    build:
      context: docker
      dockerfile: Dockerfile-db
    environment:
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB_NAME=dev_test
      - POSTGRES_SCHEMA_NAME=public
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    restart: on-failure
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  redis-messagebus:
    build:
      context: .
      dockerfile: docker/Dockerfile-redis-mbus
    depends_on:
      - redis
    env_file:
      - ./.env
    environment:
      - postgres_host=postgres
      - app_redis_url=redis
    volumes:
      - ./src:/src
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M


  # api container
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - postgres
      - redis
    env_file:
      - ./.env
    environment:
      - postgres_host=postgres
      - app_redis_url=redis
    volumes:
      - ./src:/src
    ports:
      - "8000:8000"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M

  # pytest container
  pytest:
    build:
      context: .
      dockerfile: docker/Dockerfile-pytest
    depends_on:
      postgres:
        condition: service_healthy
      api:
        condition: service_started
    env_file:
      - ./.env
    environment:
      - postgres_host=postgres
      - app_api_url=api
      - app_redis_url=redis
      - app_bus_init_need=False
    volumes:
      - ./src:/src
      - ./tests:/tests
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 128M
