FROM python:3.11-slim

COPY ../requirements.txt  /tmp/
RUN pip install -r /tmp/requirements.txt
RUN rm /tmp/requirements.txt

ENV PYTHONPATH /

CMD python /src/allocation/entrypoints/redis_event_consumer.py
